# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - snapshot
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@v2.0
        with:
          version: ${{ matrix.emacs_version }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run Tests
        run: './runtest.sh'
